### ISSUE TITLE
Async Submit and File Uploads with Dotnetify Blazor?

### ISSUE THREAD

**Issue by ghhv** [dsuryd/dotNetify-Blazor#6]
Hi Dicky, do you have a recommended way to do file uploads for web assembly apps with Dotnetify Blazor?

I tried using a Mediatr API setup I have but that required the Id for the saved record which I previously got as the return data for an async Submit action - when trying to implement return data with Dotnetify, any modification to Submit gives me this error:
```DotNetify.Blazor.TypeProxyException: Could not create proxy for 'IServerUpdateState' because method 'Submit' is not a void method.```

As a workaround to that, I tried changing Submit to an async Task and returning the Id via a state property but it still complains about being a non void method and the state does not get initialized. 
`Uncaught Error Error: Newtonsoft.Json.JsonSerializationException: Cannot deserialize {"Greetings":"Hello Friend!","Id":""} to DotNetifyBlazorBase.Client.Pages.ServerUpdateSubmit+IServerUpdateState
 ---> DotNetify.Blazor.TypeProxyException: Could not create proxy for 'IServerUpdateState' because method 'Submit' is not a void method.`

My test repository is available [here](https://github.com/ghhv/Dotnetify-Blazor-Testing)
The page I'm testing this with is [here](https://github.com/ghhv/Dotnetify-Blazor-Testing/blob/master/DotNetifyBlazorBase/Client/Pages/ServerUpdateSubmit.razor)
Server side page is [here](https://github.com/ghhv/Dotnetify-Blazor-Testing/blob/master/DotNetifyBlazorBase/Server/ViewModels/ServerUpdateSubmit.cs
)

Eventually, I'm planning to use this file upload component [https://blazor.radzen.com/example-upload](https://blazor.radzen.com/example-upload)

**Comment by ghhv** [comment]
So I found the TypeProxy code and can't see how it will ever allow a non-Void (& non Public).. 
![image](https://user-images.githubusercontent.com/13160762/173755131-fd7a0587-c827-4f3e-9ff6-a3f36bbad2b7.png)

Even your TestMethods exclude any Async options..
![image](https://user-images.githubusercontent.com/13160762/173755291-c29b4953-9e7c-4bf5-9be6-b01747a8edc8.png)

So I guess this is a bug or the documentation is incorrect?
![image](https://user-images.githubusercontent.com/13160762/173755418-561859f6-b28b-45f6-995c-39cb43ef84e8.png)

Please advise, Thanks!

**Comment by dsuryd** [comment]
The documentation is correct, but only with respect to server-side view models.  The client-side view model proxy does not support asynchronous methods as it currently has no facility to suspend execution until the server-side response is received.

**Comment by ghhv** [comment]
Yeah, I wondered about that.. makes sense now. Thanks.

**Comment by smfields** [comment]
> The documentation is correct, but only with respect to server-side view models. The client-side view model proxy does not support asynchronous methods as it currently has no facility to suspend execution until the server-side response is received.

Is supporting Task return types something that's planned to be added? This limitation causes issues with sharing the view model interface between the client and the server (one of the big benefits of using Blazor). 

Currently you can't have a `Task` return type in the interface because of the above error. You can't implement the method in the server side view model with a `Task` return type if the interface returns `void`, meaning that you have to change the return type in the interface to `void`. While async methods with `void` return types are technically valid, they cause a whole slew of issues when it comes to things like exceptions.

So at the moment the only real valid option is to have two interfaces, one for the client-side to proxy that has a `void` return type, and one for the server-side view model to implement that has a `Task` return type.
